// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SystemPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"header\"><h1>System</h1></div><div class=\"card\"><h2 style=\"margin-bottom: 20px;\">Metadata Management</h2><p style=\"color: var(--secondary-text); margin-bottom: 20px;\">Sync metadata from the One Pace Jellyfin metadata repository. This updates episode information,  artwork, and organizational data.</p><button class=\"btn btn-success\" hx-post=\"/api/system/sync\" hx-target=\"#sync-alert\" hx-swap=\"innerHTML\" onclick=\"this.disabled=true; this.innerHTML='⏳ Syncing...';\">🔄 Sync Metadata</button><div id=\"sync-alert\" style=\"margin-top: 20px;\"></div></div><div class=\"card\" style=\"margin-top: 20px;\"><h2 style=\"margin-bottom: 20px;\">System Information</h2><table class=\"table\"><tbody><tr><td><strong>Version</strong></td><td>1.0.1</td></tr><tr><td><strong>Metadata Repository</strong></td><td>tissla/one-pace-jellyfin</td></tr><tr><td><strong>Download Method</strong></td><td>Internal BitTorrent Client</td></tr></tbody></table></div><div class=\"card\" style=\"margin-top: 20px;\"><h2 style=\"margin-bottom: 20px;\">Logs</h2><div style=\"background-color: var(--primary-bg); padding: 15px; border-radius: 5px; font-family: monospace; font-size: 12px; max-height: 300px; overflow-y: auto;\"><p style=\"color: var(--secondary-text);\">Log viewing coming soon...</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SystemScript().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SystemScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\tdocument.body.addEventListener('htmx:afterSwap', function(evt) {\n\t\tif(evt.detail.target.id === 'sync-alert') {\n\t\t\tconst button = document.querySelector('button[hx-post=\"/api/system/sync\"]');\n\t\t\tbutton.disabled = false;\n\t\t\tbutton.innerHTML = '🔄 Sync Metadata';\n\t\t}\n\t});\n\n\tdocument.body.addEventListener('htmx:responseError', function(evt) {\n\t\tif(evt.detail.target.id === 'sync-alert') {\n\t\t\tconst button = document.querySelector('button[hx-post=\"/api/system/sync\"]');\n\t\t\tbutton.disabled = false;\n\t\t\tbutton.innerHTML = '🔄 Sync Metadata';\n\t\t\t\n\t\t\tevt.detail.target.innerHTML = `\n\t\t\t\t<div class=\"alert alert-danger\">\n\t\t\t\t\t❌ ${evt.detail.xhr.responseText || 'Sync failed. Please check your settings.'}\n\t\t\t\t</div>\n\t\t\t`;\n\t\t\t\n\t\t\tsetTimeout(() => {\n\t\t\t\tevt.detail.target.innerHTML = '';\n\t\t\t}, 5000);\n\t\t}\n\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
